=== jortemar/XML/SacarXML/DTD.dtd
<!ELEMENT árbol (especie)+>
<!ELEMENT especie (nombre,variedad,(origen)+,color_fruto,
(maduración)+,(riego)?,(precio)?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT variedad (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT color_fruto (#PCDATA)>
<!ELEMENT maduración (#PCDATA)>
<!ELEMENT riego (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== jortemar/XML/SacarXML/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE 치rbol SYSTEM "./DTD.dtd">

<치rbol>
    <especie>
        <nombre>pino</nombre>
        <variedad>carrasco</variedad>
        <origen>macedonia</origen>
        <origen>tailandia</origen>
        <color_fruto>rojo</color_fruto>
        <color_fruto>rojo</color_fruto>
        <maduracion>칩ptima</maduracion>
        <riego>no</riego>
        <precio>7</precio>
    </especie>
    <especie>
        <nombre>Jose</nombre>
        <variedad></variedad>
        <origen></origen>
        <color_fruto></color_fruto>
        <maduracion></maduracion>
        <riego></riego>
        <precio></precio>
    </especie>
</치rbol>
