=== jortemar/XML/Examen/03.dtd_aparte.dtd
<!-- Cuando el DTD va en un archivo aparte no es 
necesario poner el <!DOCTYPE (habrÃ¡ que ponerlo en el 
xml con la llamada a este archivo) -->

<!ELEMENT BDcomponentes (componente)+>
<!ELEMENT componente (nombre, (precio|precioiva), tipo*, medida)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT precioiva (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medida (#PCDATA)>

=== jortemar/XML/Examen/03.dtd_aparte.xml
<?xml version="1.0" encoding="UTF-8"
standalone="no"?>
<!-- Podemos usar el atributo standalone para indicar si
    el DTD es externo ("no") o interno ("yes")
    No es obligatorio  -->

<!-- Utilizamos este formato de <!DOCTYPE para llamar al archivo .dtd -->
<!DOCTYPE BDcomponentes SYSTEM "03.dtd_aparte.dtd">

<BDcomponentes>
    <componente>
        <nombre>resistencia</nombre>
        <precio>0.25</precio>
        <tipo>pasivo</tipo>
        <tipo>bobinadas</tipo>
        <medida>ohmios</medida>
    </componente>
    <componente>
        <nombre>condensador</nombre>
        <precioiva>0.75</precioiva>
        <medida>Faradios</medida>
    </componente>
</BDcomponentes>
