<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BDcomponentes [
    <!ELEMENT BDcomponentes (componente)+>
    <!ELEMENT componente (nombre, (precio|precioiva), tipo*, medida)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT precioiva (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT medida (#PCDATA)>
]>

<BDcomponentes>
    <componente>
        <nombre>resistencia</nombre>
        <precio>0.25</precio>
        <tipo>pasivo</tipo>
        <tipo>bobinadas</tipo>
        <medida>ohmios</medida>
    </componente>
    <componente>
        <nombre>condensador</nombre>
        <precioiva>0.75</precioiva>
        <medida>Faradios</medida>
    </componente>
</BDcomponentes>