<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE concesionario [
    <!ELEMENT concesionario (coche+)>
    <!ELEMENT coche (marca, modelo, color, año, precio)>
    <!ATTLIST coche combustible CDATA (D|G) #REQUIRED>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
]>

<concesionario>
    <coche combustible="D">
        <marca>Volkswagen</marca>
        <modelo>Passat</modelo>
        <color>Azul</color>
        <año>2005</año>
        <precio>7900.00</precio>
    </coche>
    <coche combustible="G">
        <marca>Volkswagen</marca>
        <modelo>Touran</modelo>
        <color>Azul</color>
        <año>2007</año>
        <precio>8200.00</precio>
    </coche>
    <coche combustible="D">
        <marca>Opel</marca>
        <modelo>Astra</modelo>
        <color>Negro</color>
        <año>2013</año>
        <precio>8490.00</precio>
    </coche>
</concesionario>