=== jortemar/XML/XSD/practica2/hojaformato2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="es">
            Archivo .xsd de ejemplo para aprender.
            sdfsdfasdfsdfsdf
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="fechainicio" type="string" maxOccurs="unbounded" minOccurs="0" />



    <xsd:element name="fp">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="ciclo" maxOccurs="unbounded" minOccurs="0" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="ciclo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="modulo" maxOccurs="unbounded" minOccurs="0" />
            </xsd:sequence>
            <xsd:attribute name="nombre" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="modulo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="fechainicio" type="xsd:string" maxOccurs="1" minOccurs="0" />
                <xsd:element name="fechafin" type="xsd:string" maxOccurs="1" minOccurs="0" />
                <xsd:element ref="alumno" maxOccurs="unbounded" minOccurs="0" />
            </xsd:sequence>
            <xsd:attribute name="nombre" type="xsd:string" />
            <xsd:attribute name="duracion" type="xsd:string" />
            <xsd:attribute name="caracter" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="alumno">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="nif" type="xsd:string" />
                <xsd:element name="direccion" type="xsd:string" />
                <xsd:element name="cp" type="xsd:integer" />
                <xsd:element name="poblacion" type="xsd:string" />
                <xsd:element name="telefono" type="xsd:integer" />
                <xsd:element name="correo" type="xsd:string" />
                <xsd:element name="faltaasistencia" type="xsd:integer" />
                <xsd:element name="calificaciones" type="xsd:string" />
            </xsd:sequence>
            <xsd:attribute name="nombre" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== jortemar/XML/EjercicioXSD/practica2/etiquetas2.xml
<?xml version="1.0" encoding="UTF-8"?>
<fp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./hojaformato2.xsd">
    <ciclo nombre="DAW">
        <modulo nombre="DAES" duracion="4 horas semanales" caracter="obligatorio">
            <fechainicio>15 de septiembre de 2022</fechainicio>
            <fechafin>30 junio de 2023</fechafin>
            <alumno nombre="Alvaro">
                <nif>1698484</nif>
                <direccion>Aqui</direccion>
                <cp>30030 </cp>
                <poblacion>santander</poblacion>
                <telefono>878798657</telefono>
                <correo>kdkdkdk@gmail.com</correo>
                <faltassistencia />
                <calificaciones />
            </alumno>

            <alumno nombre="Izan">
                <nif>8484848</nif>
                <direccion>esta</direccion>
                <cp>3942</cp>
                <poblacion>Bilbao</poblacion>
                <telefono>8676766</telefono>
                <correo>ieieieei@gmail.com</correo>
                <faltassistencia>0</faltassistencia>
                <calificaciones>aptp</calificaciones>
            </alumno>
        </modulo>
        <modulo nombre="DAWI"></modulo>
    </ciclo>
</fp>
