<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE fp[
<!ELEMENT fp (receta)+>
<!ELEMENT receta (ingredientes, proceso)+>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT proceso (paso+)>

<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT paso (#PCDATA)>
]>
<fp>

<receta>
    <ingredientes>
        <ingrediente>1 kg de cebollas</ingrediente>
        <ingrediente>2 l. de calde de carne</ingrediente>
        <ingrediente>100 mg de mantequilla</ingrediente>
        <ingrediente>1 cucharada de harina</ingrediente>
        <ingrediente>100 gr de harina</ingrediente>
        <ingrediente>Pan tostado en rebanadas</ingrediente>    
        <ingrediente>Tomillo</ingrediente>
        <ingrediente>1 hoja de laurel</ingrediente>
        <ingrediente>Pimienta</ingrediente>
    </ingredientes>
    <proceso>
        <paso>1. Pelar y partir las cebollas en rodajas finas</paso>
        <paso>2. Rehogarlas con la mantequilla, sal y pimienta a fuego lento
            hasta que estén transparentes sin dorarse</paso>    
        <paso>3. Añadir la harina sin dejar de remover</paso>
        <paso>4. Ponerlo en una cazuela con el caldo, el tomillo y el laurel</paso>
        <paso>5. Dejar cocer a fuego lento durante unos 15 minutos</paso>
        <paso>6. Poner las rebanadas de pan encima, espolvorear el queso y gratinar al horno</paso>
    </proceso>
</receta>
</fp>