<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aeropuerto[
    <!ELEMENT aeropuerto (nombre, vuelos, fecha)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT vuelos (vuelo+)>
    <!ELEMENT vuelo (diario, origen, destino, hora-salida, hora-llegada)>
    <!ATTLIST vuelo código CDATA #REQUIRED>
    <!ATTLIST vuelo estado CDATA #REQUIRED>
    <!ELEMENT diario (#PCDATA)>
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT hora-salida (#PCDATA)>
    <!ELEMENT hora-llegada (#PCDATA)>   
]>

<aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="aeropuerto.xsd">
    <nombre>JFK</nombre>
    <vuelos>
        <vuelo código="V22" estado="R">
            <diario />
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora-salida>09:30:00</hora-salida>
            <hora-llegada>11:30:00</hora-llegada>
        </vuelo>
        <vuelo código="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora-salida>10:15:00</hora-salida>
            <hora-llegada>11:15:00</hora-llegada>
        </vuelo>
    </vuelos>
    <fecha>2013-12-20</fecha>
</aeropuerto>